import type {ThemeType} from "./theme.type.ts";

export const getDefaultLightTheme = (): ThemeType => {
    // 使用随机颜色生成一个占位的浅色主题（用于开发调试）。
    // 注意：每次调用都会返回不同的颜色值。
    const randomColor = (): `#${string}` => {
        const c = Math.floor(Math.random() * 0xffffff);
        return `#${c.toString(16).padStart(6, '0')}`;
    };

    return {
        text: {
            primary: randomColor(),
            secondary: randomColor(),
            tertiary: randomColor(),
            disabled: randomColor(),
            inverse: randomColor(),
            accentPrimary: randomColor(),
            accentSecondary: randomColor(),
            accentTertiary: randomColor(),
            accentDisabled: randomColor(),
            onAccentFillColorSelectedText: randomColor(),
            onAccentFillColorPrimary: randomColor(),
            onAccentFillColorSecondary: randomColor(),
            onAccentFillColorDisabled: randomColor(),
        },
        fill: {
            controlDefault: randomColor(),
            controlSecondary: randomColor(),
            controlTertiary: randomColor(),
            controlDisabled: randomColor(),
            controlTransparent: randomColor(),
            controlInputActive: randomColor(),
            controlStrongDefault: randomColor(),
            controlStrongDisabled: randomColor(),
            controlSolidDefault: randomColor(),
            subtleTransparent: randomColor(),
            subtleSecondary: randomColor(),
            subtleTertiary: randomColor(),
            subtleDisabled: randomColor(),
            controlAltTransparent: randomColor(),
            controlAltSecondary: randomColor(),
            controlAltTertiary: randomColor(),
            controlAltQuarternary: randomColor(),
            controlAltDisabled: randomColor(),
            controlOnImageDefault: randomColor(),
            controlOnImageSecondary: randomColor(),
            controlOnImageTertiary: randomColor(),
            controlOnImageDisabled: randomColor(),
            accentSelectedTextBackground: randomColor(),
            accentDefault: randomColor(),
            accentSecondary: randomColor(),
            accentTertiary: randomColor(),
            accentDisabled: randomColor(),
            cardBackgroundDefault: randomColor(),
            cardBackgroundSecondary: randomColor(),
            smokeDefault: randomColor(),
            layerDefault: randomColor(),
            layerAlt: randomColor(),
            layerOnAcrylicDefault: randomColor(),
            layerOnAccentAcrylicDefault: randomColor(),
            layerOnMicaBaseAltDefault: randomColor(),
            layerOnMicaBaseAltSecondary: randomColor(),
            layerOnMicaBaseAltTertiary: randomColor(),
            layerOnMicaBaseAltTransparent: randomColor(),
            solidBackgroundBase: randomColor(),
            solidBackgroundSecondary: randomColor(),
            solidBackgroundTertiary: randomColor(),
            solidBackgroundQuarternary: randomColor(),
            solidBackgroundBaseAlt: randomColor(),
        },
        stroke: {
            controlDefault: randomColor(),
            controlSecondary: randomColor(),
            controlOnAccentDefault: randomColor(),
            controlOnAccentSecondary: randomColor(),
            controlOnAccentTertiary: randomColor(),
            controlOnAccentDisabled: randomColor(),
            controlForStrongFillWhenOnImage: randomColor(),
            cardDefault: randomColor(),
            cardDefaultSolid: randomColor(),
            controlStrongDefault: randomColor(),
            controlStrongDisabled: randomColor(),
            surfaceDefault: randomColor(),
            surfaceFlyout: randomColor(),
            surfaceInverse: randomColor(),
            dividerDefault: randomColor(),
            focusOuter: randomColor(),
            focusInner: randomColor(),
        },
        system: {
            attention: randomColor(),
            success: randomColor(),
            caution: randomColor(),
            critical: randomColor(),
            neutral: randomColor(),
            solidNeutral: randomColor(),
            attentionBackground: randomColor(),
            successBackground: randomColor(),
            cautionBackground: randomColor(),
            criticalBackground: randomColor(),
            neutralBackground: randomColor(),
            solidAttentionBackground: randomColor(),
            solidNeutralBackground: randomColor(),
        },
        highContrast: {
            systemColorWindowTextColor: randomColor(),
            systemColorWindowColor: randomColor(),
            systemColorButtonFaceColor: randomColor(),
            systemColorButtonTextColor: randomColor(),
            systemColorHighlightColor: randomColor(),
            systemColorHighlightTextColor: randomColor(),
            systemColorHotlightColor: randomColor(),
            systemColorGrayTextColor: randomColor(),
            ControlElevationBorder: randomColor(),
            CircleElevationBorder: randomColor(),
            AccentControlElevationBorder: randomColor(),
        },
    }
}