/**
 * @fileOverview 主题的类型定义
 */

export interface ThemeColor {
    text: {
        primary: string
        secondary: string
        tertiary: string
        disabled: string
        inverse: string
        accentPrimary: string
        accentSecondary: string
        accentTertiary: string
        accentDisabled: string
        onAccentFillColorSelectedText: string
        onAccentFillColorPrimary: string
        onAccentFillColorSecondary: string
        onAccentFillColorDisabled: string
    },
    fill: {
        ControlDefault: string
        ControlSecondary: string
        ControlTertiary: string
        ControlDisabled: string
        ControlTransparent: string
        ControlInputActive: string
        ControlStrongDefault: string
        ControlStrongDisabled: string
        ControlSolidDefault: string
        SubtleTransparent: string
        SubtleSecondary: string
        SubtleTertiary: string
        SubtleDisabled: string
        ControlAltTransparent: string
        ControlAltSecondary: string
        ControlAltTertiary: string
        ControlAltQuarternary: string
        ControlAltDisabled: string
        ControlOnImageDefault: string
        ControlOnImageSecondary: string
        ControlOnImageTertiary: string
        ControlOnImageDisabled: string
        AccentSelectedTextBackground: string
        AccentDefault: string
        AccentSecondary: string
        AccentTertiary: string
        AccentDisabled: string
        CardBackgroundDefault: string
        CardBackgroundSecondary: string
        SmokeDefault: string
        LayerDefault: string
        LayerAlt: string
        LayerOnAcrylicDefault: string
        LayerOnAccentAcrylicDefault: string
        LayerOnMicaBaseAltDefault: string
        LayerOnMicaBaseAltSecondary: string
        LayerOnMicaBaseAltTertiary: string
        LayerOnMicaBaseAltTransparent: string
        SolidBackgroundBase: string
        SolidBackgroundSecondary: string
        SolidBackgroundTertiary: string
        SolidBackgroundQuarternary: string
        SolidBackgroundBaseAlt: string
    }
    stroke: {
        ControlDefault: string
        ControlSecondary: string
        ControlOnAccentDefault: string
        ControlOnAccentSecondary: string
        ControlOnAccentTertiary: string
        ControlOnAccentDisabled: string
        ControlForStrongFillWhenOnImage: string
        CardDefault: string
        CardDefaultSolid: string
        ControlStrongDefault: string
        ControlStrongDisabled: string
        SurfaceDefault: string
        SurfaceFlyout: string
        SurfaceInverse: string
        DividerDefault: string
        FocusOuter: string
        FocusInner: string
    }
    system: {
        attention: string
        success: string
        caution: string
        critical: string
        neutral: string
        solidNeutral: string
        attentionBackground: string
        successBackground: string
        cautionBackground: string
        criticalBackground: string
        neutralBackground: string
        solidAttentionBackground: string
        solidNeutralBackground: string
        // 这是干什么的？归类也在这边吗？
        ColorWindowTextColor: string
        ColorWindowColor: string
        ColorButtonFaceColor: string
        ColorButtonTextColor: string
        ColorHighlightColor: string
        ColorHighlightTextColor: string
        ColorHotlightColor: string
        ColorGrayTextColor: string
    }
}