/**
 * @fileOverview 主题的类型定义
 */

export interface ThemeColor {
    text: {
        TextFillColorPrimary: string
        TextFillColorSecondary: string
        TextFillColorTertiary: string
        TextFillColorDisabled: string
        TextFillColorInverse: string
        AccentTextFillColorPrimary: string
        AccentTextFillColorSecondary: string
        AccentTextFillColorTertiary: string
        AccentTextFillColorDisabled: string
        TextOnAccentFillColorSelectedText: string
        TextOnAccentFillColorPrimary: string
        TextOnAccentFillColorSecondary: string
        TextOnAccentFillColorDisabled: string
    },

    ControlFillColorDefault: string
    ControlFillColorSecondary: string
    ControlFillColorTertiary: string
    ControlFillColorDisabled: string
    ControlFillColorTransparent: string
    ControlFillColorInputActive: string
    ControlStrongFillColorDefault: string
    ControlStrongFillColorDisabled: string
    ControlSolidFillColorDefault: string
    SubtleFillColorTransparent: string
    SubtleFillColorSecondary: string
    SubtleFillColorTertiary: string
    SubtleFillColorDisabled: string
    ControlAltFillColorTransparent: string
    ControlAltFillColorSecondary: string
    ControlAltFillColorTertiary: string
    ControlAltFillColorQuarternary: string
    ControlAltFillColorDisabled: string
    ControlOnImageFillColorDefault: string
    ControlOnImageFillColorSecondary: string
    ControlOnImageFillColorTertiary: string
    ControlOnImageFillColorDisabled: string
    AccentFillColorSelectedTextBackground: string
    AccentFillColorDefault: string
    AccentFillColorSecondary: string
    AccentFillColorTertiary: string
    AccentFillColorDisabled: string
    ControlStrokeColorDefault: string
    ControlStrokeColorSecondary: string
    ControlStrokeColorOnAccentDefault: string
    ControlStrokeColorOnAccentSecondary: string
    ControlStrokeColorOnAccentTertiary: string
    ControlStrokeColorOnAccentDisabled: string
    ControlStrokeColorForStrongFillWhenOnImage: string
    CardStrokeColorDefault: string
    CardStrokeColorDefaultSolid: string
    ControlStrongStrokeColorDefault: string
    ControlStrongStrokeColorDisabled: string
    SurfaceStrokeColorDefault: string
    SurfaceStrokeColorFlyout: string
    SurfaceStrokeColorInverse: string
    DividerStrokeColorDefault: string
    FocusStrokeColorOuter: string
    FocusStrokeColorInner: string
    CardBackgroundFillColorDefault: string
    CardBackgroundFillColorSecondary: string
    SmokeFillColorDefault: string
    LayerFillColorDefault: string
    LayerFillColorAlt: string
    LayerOnAcrylicFillColorDefault: string
    LayerOnAccentAcrylicFillColorDefault: string
    LayerOnMicaBaseAltFillColorDefault: string
    LayerOnMicaBaseAltFillColorSecondary: string
    LayerOnMicaBaseAltFillColorTertiary: string
    LayerOnMicaBaseAltFillColorTransparent: string
    SolidBackgroundFillColorBase: string
    SolidBackgroundFillColorSecondary: string
    SolidBackgroundFillColorTertiary: string
    SolidBackgroundFillColorQuarternary: string
    SolidBackgroundFillColorBaseAlt: string
    system: {
        FillColorAttention: string
        FillColorSuccess: string
        FillColorCaution: string
        FillColorCritical: string
        FillColorNeutral: string
        FillColorSolidNeutral: string
        FillColorAttentionBackground: string
        FillColorSuccessBackground: string
        FillColorCautionBackground: string
        FillColorCriticalBackground: string
        FillColorNeutralBackground: string
        FillColorSolidAttentionBackground: string
        FillColorSolidNeutralBackground: string
        ColorWindowTextColor: string
        ColorWindowColor: string
        ColorButtonFaceColor: string
        ColorButtonTextColor: string
        ColorHighlightColor: string
        ColorHighlightTextColor: string
        ColorHotlightColor: string
        ColorGrayTextColor: string
    }
}