// noinspection JSUnusedGlobalSymbols

interface theme {
    // TextFillColorPrimary
    TextFillColorPrimary: "#FFFFFF"
    // TextFillColorSecondary(重新格式化)
    TextFillColorSecondary: "#FFFFFFC5"
    // TextFillColorTertiary(重新格式化)
    TextFillColorTertiary: "#FFFFFF87"
    // TextFillColorDisabled(重新格式化)
    TextFillColorDisabled: "#FFFFFF5D"
    // TextFillColorInverse(重新格式化)
    TextFillColorInverse: "#000000E4"
    // AccentTextFillColorDisabled(重新格式化)
    AccentTextFillColorDisabled: "#FFFFFF5D"
    // TextOnAccentFillColorSelectedText
    TextOnAccentFillColorSelectedText: "#FFFFFF"
    // TextOnAccentFillColorPrimary
    TextOnAccentFillColorPrimary: "#000000"
    // TextOnAccentFillColorSecondary(重新格式化)
    TextOnAccentFillColorSecondary: "#00000080"
    // TextOnAccentFillColorDisabled(重新格式化)
    TextOnAccentFillColorDisabled: "#FFFFFF87"
    // ControlFillColorDefault(重新格式化)
    ControlFillColorDefault: "#FFFFFF0F"
    // ControlFillColorSecondary(重新格式化)
    ControlFillColorSecondary: "#FFFFFF15"
    // ControlFillColorTertiary(重新格式化)
    ControlFillColorTertiary: "#FFFFFF08"
    // ControlFillColorDisabled(重新格式化)
    ControlFillColorDisabled: "#FFFFFF0B"
    // ControlFillColorTransparent(重新格式化)
    ControlFillColorTransparent: "#FFFFFF00"
    // ControlFillColorInputActive(重新格式化)
    ControlFillColorInputActive: "#1E1E1EB3"
    // ControlStrongFillColorDefault(重新格式化)
    ControlStrongFillColorDefault: "#FFFFFF8B"
    // ControlStrongFillColorDisabled(重新格式化)
    ControlStrongFillColorDisabled: "#FFFFFF3F"
    // ControlSolidFillColorDefault
    ControlSolidFillColorDefault: "#454545"
    // SubtleFillColorTransparent(重新格式化)
    SubtleFillColorTransparent: "#FFFFFF00"
    // SubtleFillColorSecondary(重新格式化)
    SubtleFillColorSecondary: "#FFFFFF0F"
    // SubtleFillColorTertiary(重新格式化)
    SubtleFillColorTertiary: "#FFFFFF0A"
    // SubtleFillColorDisabled(重新格式化)
    SubtleFillColorDisabled: "#FFFFFF00"
    // ControlAltFillColorTransparent(重新格式化)
    ControlAltFillColorTransparent: "#FFFFFF00"
    // ControlAltFillColorSecondary(重新格式化)
    ControlAltFillColorSecondary: "#00000019"
    // ControlAltFillColorTertiary(重新格式化)
    ControlAltFillColorTertiary: "#FFFFFF0B"
    // ControlAltFillColorQuarternary(重新格式化)
    ControlAltFillColorQuarternary: "#FFFFFF12"
    // ControlAltFillColorDisabled(重新格式化)
    ControlAltFillColorDisabled: "#FFFFFF00"
    // ControlOnImageFillColorDefault(重新格式化)
    ControlOnImageFillColorDefault: "#1C1C1CB3"
    // ControlOnImageFillColorSecondary
    ControlOnImageFillColorSecondary: "#1A1A1A"
    // ControlOnImageFillColorTertiary
    ControlOnImageFillColorTertiary: "#131313"
    // ControlOnImageFillColorDisabled
    ControlOnImageFillColorDisabled: "#1E1E1E"
    // AccentFillColorDisabled(重新格式化)
    AccentFillColorDisabled: "#FFFFFF28"
    // ControlStrokeColorDefault(重新格式化)
    ControlStrokeColorDefault: "#FFFFFF12"
    // ControlStrokeColorSecondary(重新格式化)
    ControlStrokeColorSecondary: "#FFFFFF18"
    // ControlStrokeColorOnAccentDefault(重新格式化)
    ControlStrokeColorOnAccentDefault: "#FFFFFF14"
    // ControlStrokeColorOnAccentSecondary(重新格式化)
    ControlStrokeColorOnAccentSecondary: "#00000023"
    // ControlStrokeColorOnAccentTertiary(重新格式化)
    ControlStrokeColorOnAccentTertiary: "#00000037"
    // ControlStrokeColorOnAccentDisabled(重新格式化)
    ControlStrokeColorOnAccentDisabled: "#00000033"
    // ControlStrokeColorForStrongFillWhenOnImage(重新格式化)
    ControlStrokeColorForStrongFillWhenOnImage: "#0000006B"
    // CardStrokeColorDefault(重新格式化)
    CardStrokeColorDefault: "#00000019"
    // CardStrokeColorDefaultSolid
    CardStrokeColorDefaultSolid: "#1C1C1C"
    // ControlStrongStrokeColorDefault(重新格式化)
    ControlStrongStrokeColorDefault: "#FFFFFF8B"
    // ControlStrongStrokeColorDisabled(重新格式化)
    ControlStrongStrokeColorDisabled: "#FFFFFF28"
    // SurfaceStrokeColorDefault(重新格式化)
    SurfaceStrokeColorDefault: "#75757566"
    // SurfaceStrokeColorFlyout(重新格式化)
    SurfaceStrokeColorFlyout: "#00000033"
    // SurfaceStrokeColorInverse(重新格式化)
    SurfaceStrokeColorInverse: "#0000000F"
    // DividerStrokeColorDefault(重新格式化)
    DividerStrokeColorDefault: "#FFFFFF15"
    // FocusStrokeColorOuter
    FocusStrokeColorOuter: "#FFFFFF"
    // FocusStrokeColorInner(重新格式化)
    FocusStrokeColorInner: "#000000B3"
    // CardBackgroundFillColorDefault(重新格式化)
    CardBackgroundFillColorDefault: "#FFFFFF0D"
    // CardBackgroundFillColorSecondary(重新格式化)
    CardBackgroundFillColorSecondary: "#FFFFFF08"
    // SmokeFillColorDefault(重新格式化)
    SmokeFillColorDefault: "#0000004D"
    // LayerFillColorDefault(重新格式化)
    LayerFillColorDefault: "#3A3A3A4C"
    // LayerFillColorAlt(重新格式化)
    LayerFillColorAlt: "#FFFFFF0D"
    // LayerOnAcrylicFillColorDefault(重新格式化)
    LayerOnAcrylicFillColorDefault: "#FFFFFF09"
    // LayerOnAccentAcrylicFillColorDefault(重新格式化)
    LayerOnAccentAcrylicFillColorDefault: "#FFFFFF09"
    // LayerOnMicaBaseAltFillColorDefault(重新格式化)
    LayerOnMicaBaseAltFillColorDefault: "#3A3A3A73"
    // LayerOnMicaBaseAltFillColorSecondary(重新格式化)
    LayerOnMicaBaseAltFillColorSecondary: "#FFFFFF0F"
    // LayerOnMicaBaseAltFillColorTertiary
    LayerOnMicaBaseAltFillColorTertiary: "#2C2C2C"
    // LayerOnMicaBaseAltFillColorTransparent(重新格式化)
    LayerOnMicaBaseAltFillColorTransparent: "#FFFFFF00"
    // SolidBackgroundFillColorBase
    SolidBackgroundFillColorBase: "#202020"
    // SolidBackgroundFillColorSecondary
    SolidBackgroundFillColorSecondary: "#1C1C1C"
    // SolidBackgroundFillColorTertiary
    SolidBackgroundFillColorTertiary: "#282828"
    // SolidBackgroundFillColorQuarternary
    SolidBackgroundFillColorQuarternary: "#2C2C2C"
    // SolidBackgroundFillColorTransparent(重新格式化)
    SolidBackgroundFillColorTransparent: "#20202000"
    // SolidBackgroundFillColorBaseAlt
    SolidBackgroundFillColorBaseAlt: "#0A0A0A"
    // SystemFillColorSuccess
    SystemFillColorSuccess: "#6CCB5F"
    // SystemFillColorCaution
    SystemFillColorCaution: "#FCE100"
    // SystemFillColorCritical
    SystemFillColorCritical: "#FF99A4"
    // SystemFillColorNeutral(重新格式化)
    SystemFillColorNeutral: "#FFFFFF8B"
    // SystemFillColorSolidNeutral
    SystemFillColorSolidNeutral: "#9D9D9D"
    // SystemFillColorAttentionBackground(重新格式化)
    SystemFillColorAttentionBackground: "#FFFFFF08"
    // SystemFillColorSuccessBackground
    SystemFillColorSuccessBackground: "#393D1B"
    // SystemFillColorCautionBackground
    SystemFillColorCautionBackground: "#433519"
    // SystemFillColorCriticalBackground
    SystemFillColorCriticalBackground: "#442726"
    // SystemFillColorNeutralBackground(重新格式化)
    SystemFillColorNeutralBackground: "#FFFFFF08"
    // SystemFillColorSolidAttentionBackground
    SystemFillColorSolidAttentionBackground: "#2E2E2E"
    // SystemFillColorSolidNeutralBackground
    SystemFillColorSolidNeutralBackground: "#2E2E2E"

}